# Meta schema

################################################################################
# PURPOSE

# Schema for modelling grakn schema

################################################################################
# DESCRIPTION

################################################################################
# EXAMPLES

################################################################################
# USAGE

################################################################################
# REFERENCES

#TODO link to doc

################################################################################
#NOTE

################################################################################
# STATUS

################################################################################
################################################################################

define

  ################
  ################
  ## ENTITIES ##
  ################
  ################

  node sub entity,
    has name,
    has grakn-note,
    has status,
    abstract;

  grakn-type sub node,
    has ontology,
    has ontology-version-IRI,
    has purl,
    has definition,
    has elucidation,
    has ontology-note,
    has example,
    has reference,
    has issues,
    has isabstract,
    plays parent,
    plays child,
    plays playing-role,
    plays has-attribute,
    abstract;

  type-entity sub grakn-type;

  type-relation sub grakn-type,
    plays is-relation;
    
  type-attribute sub grakn-type,
    plays is-attribute-of,
    has attr-value;
    
  grakn-rule sub node,
    has condition-when,
    has condition-then;

  ################
  ################
  ## RELATIONS ##
  ################
  ################

  edge sub relation,
    has name,
    has grakn-note,
    has status,
    abstract;

  # NB: this may screw up the graph layout
  roleplaying sub edge,
    has ontology,
    has ontology-version-IRI,
    has definition,
    has elucidation,
    has purl,
    has reference,
    has example,
    has ontology-note,
    has issues,
    relates playing-role,
    relates is-relation;

  having-attribute sub edge,
    relates has-attribute,
    relates is-attribute-of;

  parentship sub edge,
    relates parent,
    relates child;

################
################
## ATTRIBUTES ##
################
################

ontology sub attribute,
  value string;

ontology-version-IRI sub attribute,
  value string;

definition sub attribute,
  value string;

elucidation sub attribute,
  value string;

purl sub attribute,
  value string;

example sub attribute,
  value string;

reference sub attribute,
  value string;

ontology-note sub attribute,
  value string;

issues sub attribute,
  value string;

grakn-note sub attribute,
  value string;

status sub attribute,
  value string;

condition-when sub attribute,
  value string;

condition-then sub attribute,
  value string;

isabstract sub attribute,
  value boolean;

name sub attribute,
  value string;

attr-value sub attribute,
  value string;
################
################
## RULES ##
################
################
